development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: epd_development
  pool:     5
  username: epduser
  password: password1
  template: template0
test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: epd_test
  pool:     5
  username: epduser
  password: password1
  template: template0